"""part2a sede coordinator principal and tutor specialty

Revision ID: 7fb2a9a545a7
Revises: 407858b8a29f
Create Date: 2026-07-12 12:59:13.662145
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fb2a9a545a7'
down_revision: str | None = '407858b8a29f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sede_coordinator_profiles', schema=None) as batch_op:
        # server_default keeps existing rows valid (they become principal) when
        # adding a NOT NULL column to a populated table (SQLite batch mode).
        batch_op.add_column(
            sa.Column('is_principal', sa.Boolean(), nullable=False,
                      server_default=sa.true())
        )

    with op.batch_alter_table('tutor_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialty', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutor_profiles', schema=None) as batch_op:
        batch_op.drop_column('specialty')

    with op.batch_alter_table('sede_coordinator_profiles', schema=None) as batch_op:
        batch_op.drop_column('is_principal')

    # ### end Alembic commands ###
